---
language: node_js
node_js:
  - "6"

sudo: false

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install

script:
  - yarn test
